### ISSUE TITLE
Line numbers in popup off by one

### ISSUE THREAD

**Issue by z4ha** [SublimeLinter/SublimeLinter3#606] opened 2017-08-18 01:40 UTC
Line numering is off by one.

![wrong line number in pop out window](https://user-images.githubusercontent.com/26235879/29440634-e4bcc6e6-83c6-11e7-82e6-b3982f3ba91e.png)

**Comment by braver** [comment] 2017-09-22 15:27
Confirmed in ST 3143, SL 3.8.0

<img width="831" alt="screen shot 2017-09-22 at 17 25 45" src="https://user-images.githubusercontent.com/2543659/30751976-3c8558c4-9fbb-11e7-8d7d-62f0472b8b34.png">

**Comment by braver** [comment] 2017-09-22 15:40
duplicate of #560

**Closed by braver** 2017-09-22 15:40 UTC
Labels: bug
