### ISSUE TITLE
Cannot read property 'block' of undefined.   rules.js

### ISSUE THREAD

**Issue by PlanetPush** [SublimeLinter/SublimeLinter3#621] opened 2017-09-26 14:48 UTC
Hello

I'm running bemlint v1.6.0 in SublimeText 3 (Build 3143).
I'm seeing the below in the debug console.

Anyone else experiencing this issue?
Thanks
James
------------------------------------------------------------------------------------------------------------

SublimeLinter: ENV['GEM_HOME'] = 'None' 
SublimeLinter: eslint skipped 'C:\wamp64\www\node_modules\bemlint\lib\rules.js', excluded by '**/node_modules/**/*.js' 
Package Control: Skipping automatic upgrade, last run at 2017-09-26 11:20:11, next run at 2017-09-26 12:20:11 or after
SublimeLinter: bemlint: index.html ['C:\\wamp64\\www\\node_modules\\.bin\\bemlint.cmd', '@', '--format', 'compact'] 
SublimeLinter: bemlint output:
C:\wamp64\www\node_modules\bemlint\lib\rules.js:54
                if ( currentbemObj && currentbemObj.block == bemObj.block &&
                                                                   ^

TypeError: Cannot read property 'block' of undefined
    at Object.valid (C:\wamp64\www\node_modules\bemlint\lib\rules.js:54:68)
    at new ruleValidator (C:\wamp64\www\node_modules\bemlint\lib\rule-validator.js:29:40)
    at new Message (C:\wamp64\www\node_modules\bemlint\lib\message.js:20:16)
    at validate (C:\wamp64\www\node_modules\bemlint\lib\bemlint.js:102:27)
    at Parser.validateString (C:\wamp64\www\node_modules\bemlint\lib\bemlint.js:165:17)
    at new Parser (C:\wamp64\www\node_modules\bemlint\lib\bemlint.js:195:18)
    at EventEmitter.module.exports.api.verify (C:\wamp64\www\node_modules\bemlint\lib\bemlint.js:46:24)
    at processText (C:\wamp64\www\node_modules\bemlint\lib\cli-engine.js:134:24)
    at processFile (C:\wamp64\www\node_modules\bemlint\lib\cli-engine.js:162:18)
    at executeOnFile (C:\wamp64\www\node_modules\bemlint\lib\cli-engine.js:498:23)

**Comment by groteworld** [comment] 2017-09-28 14:40
I see this was also posted at https://github.com/DesTincT/bemlint/issues/6

That is a better place for it until we can determine that this is something specifically with SublimeLinter3. If it is the fix would probably happen in https://github.com/DesTincT/SublimeLinter-contrib-bemlint

I'm going to close this as this is out of scope for SL3 for now. Feel free to open this when/if the issue is with SublimeLinter core

**Closed by groteworld** 2017-09-28 14:40 UTC

**Comment by PlanetPush** [comment] 2017-09-29 08:32
Hi Blake
Thanks for your reply.  I'm a bit of a novice with these linting tools so apologies if any of the questions below are a bit 'noddy'...
Can I ask - what is it that makes it out of scope?  I'd have thought the linter should be able to handle the type of mark-up in my example.
I'm actually a little confused as to where the issue lies so was unsure where to post the issue.Is it in bemlint or SublimeLinter or is it in DesTincT/SublimeLinter-contrib-bemlint or is it elsewhere?
I work in a team of 10 interface devs and a handful are experiencing the same issue in that our linting icons don't always appear.   Until recently everything worked fine and none of us experienced any linting issues.  I suspect this is a version related issue with different versions of different things not playing nicely together,
The bigger worry for the wider audience is that many others devs won't even notice their linting isn't working - they'll just assume their mark-up is spot on whilst the code falls over silently in the background.
Whilst this issue is being looked at would you recommend we reverted to a certain version?
CheersJames
