### ISSUE TITLE
PATH issue or something + Cannot save user settings

### ISSUE THREAD

**Issue by narthur157** [SublimeLinter/SublimeLinter3#514] opened 2016-11-21 19:46 UTC
```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/fractalguest/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 278, in on_activated
    self.check_syntax(view)
  File "/Users/fractalguest/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 205, in check_syntax
    Linter.assign(view, reset=True)
  File "/Users/fractalguest/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
    if not linter_class.disabled and linter_class.can_lint(syntax):
  File "./python3.3/functools.py", line 251, in wrapper
  File "/Users/fractalguest/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
    status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
UnboundLocalError: local variable 'executable' referenced before assignment
reloading settings Packages/User/SublimeLinter.sublime-settings
```

This happens to me when I open a file type that should be linted. Additionally, if I make a change to my user settings, they are overriden upon reload.

**Comment by braver** [comment] 2017-11-22 14:53
duplicate of #491

**Closed by braver** 2017-11-22 14:53 UTC
