### ISSUE TITLE
Project settings doesn't recognize "SublimeLinter": {"paths": {...}}

### ISSUE THREAD

**Issue by fredrikaverpil** [SublimeLinter/SublimeLinter3#533] opened 2017-01-13 19:06 UTC
I have this in `my_project.sublime-project`:

```json
{
    "SublimeLinter":
     {
        "paths": {
            "linux": [],
            "osx": ["/Users/fredrik/condaenvs/mycondaenv/bin/"],
            "windows": []
        }
    }
}
```

But the linter (in my case pylint) isn't being picked up.

It works great if I specify that exact condaenv path in the global settings.

**Comment by cztoky** [comment] 2017-01-19 15:55
Hi, same problem for me. :-/

**Comment by braver** [comment] 2017-10-03 08:45
This a duplicate of #32: it's currently not possible to set paths in projects: http://www.sublimelinter.com/en/latest/settings.html#project-settings

**Closed by braver** 2017-10-03 08:45 UTC
Labels: bug
