### ISSUE TITLE
[feature request] Use Phantoms API to display errors/warning

### ISSUE THREAD

**Issue by flashios09** [SublimeLinter/SublimeLinter3#520] opened 2016-12-12 01:51 UTC
Hi, 

Instead of displaying the error/warning in the **status bar** like this:

![image](https://cloud.githubusercontent.com/assets/1313482/21085654/b285183e-c014-11e6-856b-6dec488c7a3d.png)

Why we don't use the [Phantoms Api](http://www.sublimetext.com/docs/3/api_reference.html#sublime.Phantom) to display the **error/warning** like this:

![image](https://cloud.githubusercontent.com/assets/1313482/21085676/f2f37e92-c014-11e6-9864-42069d7d5f8a.png)

This is the blog post from the official ST website:
https://www.sublimetext.com/blog/articles/sublime-text-3-build-3124

Thanks

**Comment by groteworld** [comment] 2016-12-12 02:08
duplicate of #470

**Closed by groteworld** 2016-12-12 02:08 UTC
