### ISSUE TITLE
lint_mode for specific plugin

### ISSUE THREAD

**Issue by LeonardoGentile** [SublimeLinter/SublimeLinter3#472] opened 2016-06-29 11:18 UTC
Hi, 
I've read the docs but I couldn't find this options, that's why I'm asking:
is it possible to use different `lint_mode` for the different plugins?

This is my use case: When I open the files I'd like the comment annotations as "TODO" "TOFIX" to be highlighted, so in this case the correct _lint_mode_ for _SublimeLinter-annotations_ would be `load/save` or `background`. The problem is that when I am working on a file, say python (with _SublimeLinter-pylint_) I don't want to be distracted by other warnings or errors that are not relevant for the moment so I would chose a _lint_mode_ `manual` while still having the todos annotation highlighted.

Is this possible?

**Comment by braver** [comment] 2017-10-05 18:02
This is a duplicate of #244. Currently global settings like lint_mode cannot be specified per linter.

**Closed by braver** 2017-10-05 18:02 UTC
